In [3]:
import numpy as np

arr=np.array([1,2,'aman',3,4,5])
print(arr)
print(arr.shape)

['1' '2' 'aman' '3' '4' '5']
(6,)


In [9]:
brr=np.array([[1],[2],[3],[4],[5]])
print(brr.shape)
print(brr[1][0])

(5, 1)
2


In [11]:
crr=np.array([[1,2,3],[4,5,6]])
print(crr.shape)
print(crr[0])
print(crr[1][2])

(2, 3)
[1 2 3]
6


In [12]:
a=np.zeros((4,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
c=np.full((3,3),7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [17]:
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
random_mat=np.random.random((3,3))
print(random_mat)

[[0.6358213  0.91049401 0.88758495]
 [0.0879682  0.97596386 0.15135646]
 [0.12145785 0.37462908 0.075947  ]]


In [25]:
# For all the rows print coloumn 1
print(random_mat[:,1])

[0.91049401 0.97596386 0.37462908]


In [26]:
# All the coloumns of row 1

random_mat[1,:]=1
print(random_mat)

[[0.6358213  0.91049401 0.88758495]
 [1.         1.         1.        ]
 [0.12145785 0.37462908 0.075947  ]]


In [27]:
c=np.zeros((4,4))

# For first row all the cols
c[1,:]=5
print(c)

[[0. 0. 0. 0.]
 [5. 5. 5. 5.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
# All rows only last col
c[:,-1]=6
print(c)

[[0. 0. 0. 6.]
 [5. 5. 5. 6.]
 [0. 0. 0. 6.]
 [0. 0. 0. 6.]]


In [30]:
# We can also change the data type


z=np.zeros((3,3))
print(z.dtype)
z=np.zeros((3,3),dtype=np.int64)
print(z.dtype)

float64
int64


In [31]:
# Addition of numpy array
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [32]:
# Subtraction
print(x-y)
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [33]:
print(np.multiply(x,y))
x.dot(y)

[[ 5 12]
 [21 32]]


array([[19, 22],
       [43, 50]])

In [34]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [35]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [36]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

# It has converted b to 4*1 i.e a is 1*4 and b is 4*1
print(a.dot(b))
print(sum(a))

30
10


In [37]:
print(np.sum(x))

# Along columns
print(np.sum(x,axis=0))


# Along Rows
print(np.sum(x,axis=1))

10
[4 6]
[3 7]


In [38]:
# Stacking of array

a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
b=b*2
print(b)


[2 4 6 8]


In [39]:
np.stack((a,b),axis=1)

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [40]:
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [48]:
z=np.stack((a,b),axis=0)
print(z.shape)

(2, 4)


In [49]:
print(z)

[[1 2 3 4]
 [2 4 6 8]]


In [50]:
z=z.reshape((4,2))
print(z)

[[1 2]
 [3 4]
 [2 4]
 [6 8]]


In [51]:
z=z.reshape((8,1))
print(z)

[[1]
 [2]
 [3]
 [4]
 [2]
 [4]
 [6]
 [8]]


In [52]:
# If we dont know how many cols are there then write -1
#  Then Computer will automatically figure it out how many cols are there

z=z.reshape((4,-1))
print(z)

[[1 2]
 [3 4]
 [2 4]
 [6 8]]
